#ifndef NETUDP_TOKEN_H
#define NETUDP_TOKEN_H

/**
 * @file netudp_token.h
 * @brief Connect token generation for netudp.
 *        Tokens are generated by the game backend and sent to clients via HTTPS.
 */

#include "netudp_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Generate a connect token for a client.
 *
 * @param num_server_addresses Number of server addresses (1-32)
 * @param server_addresses     Array of "host:port" strings
 * @param expire_seconds       Token lifetime in seconds
 * @param timeout_seconds      Connection timeout in seconds
 * @param client_id            Unique client identifier
 * @param protocol_id          Unique game/protocol identifier
 * @param private_key          32-byte shared key (same on server)
 * @param user_data            256 bytes of application data (NULL = zeros)
 * @param connect_token        Output: 2048-byte connect token
 *
 * @return NETUDP_OK on success, NETUDP_ERROR_INVALID_PARAM on bad input.
 */
int netudp_generate_connect_token(
    int            num_server_addresses,
    const char**   server_addresses,
    int            expire_seconds,
    int            timeout_seconds,
    uint64_t       client_id,
    uint64_t       protocol_id,
    const uint8_t  private_key[32],
    uint8_t        user_data[256],
    uint8_t        connect_token[2048]
);

#ifdef __cplusplus
}
#endif

#endif /* NETUDP_TOKEN_H */
